services:
  db:
    image: postgres:15-alpine
    container_name: order_food_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev  
    container_name: order_food_backend
    restart: always
    ports:
      - "8010:8010"
    volumes:
      - ./core:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8010 --reload
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  db_data:
